Assignment 1

Aishita Kumar, 102303744

Q1: Questions on Basic NumPy Array:

In [1]:
import numpy as np

(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])


In [ ]:
array = np.array([1, 2, 3, 6, 4, 5])
rev_arr = array[::-1]
print(rev_arr)

[5 4 6 3 2 1]


(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two NumPy in-built methods

In [ ]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

flat1 = array1.flatten()
print(flat1)

flat2 = array1.ravel()
print(flat2)

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


(c) Compare the following numpy arrays:
        arr1 = np.array([[1, 2], [3, 4]])
        arr2 = np.array([[1, 2], [3, 4]])

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

print(np.array_equal(arr1, arr2)) 

print((arr1 == arr2).all())       


True
True


(d) Find the most frequent value and their indice(s) in the following arrays:

    i. x = np.array([1,2,3,4,5,1,2,1,1,1])
    ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 


In [ ]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
unique, counts = np.unique(x, return_counts=True)
mostfreq = unique[np.argmax(counts)]
indicesx = np.where(x == mostfreq)[0]
print("Most frequent in x:", mostfreq, "| Indices:", indicesx)

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
unique, counts = np.unique(y, return_counts=True)
mostfreq = unique[np.argmax(counts)]
indicesy = np.where(y == mostfreq)[0]
print("Most frequent in y:", mostfreq, "| Indices:", indicesy)


Most frequent in x: 1 | Indices: [0 5 7 8 9]
Most frequent in y: 1 | Indices: [0 1 2]


(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find

    i. Sum of all elements 
    ii. Sum of all elements row-wise
    iii. Sum of all elements column-wise

In [8]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

sum=gfg.sum()
print("Total sum:", sum)

rowsum=gfg.sum(axis=1)
print("Row-wise sum:\n", rowsum)

colsum=gfg.sum(axis=0)
print("Column-wise sum:\n",colsum )


Total sum: 45
Row-wise sum:
 [[14]
 [16]
 [15]]
Column-wise sum:
 [[20  9 16]]


(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find

    i. Sum of diagonal elements
    ii. Eigen values of matrix
    iii. Eigen vectors of matrix
    iv. Inverse of matrix
    v. Determinant of matrix 


In [7]:
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])

diasum=np.trace(n_array)
print("Diagonal sum:", diasum)

eigenvals = np.linalg.eigvals(n_array)
print("Eigenvalues:\n", eigenvals)

eigenvals, eigenvecs = np.linalg.eig(n_array)
print("Eigenvectors:\n", eigenvecs)

inverse = np.linalg.inv(n_array)
print("Inverse:\n", inverse)

det = np.linalg.det(n_array)
print("Determinant:", det)


Diagonal sum: 176
Eigenvalues:
 [98.16835147 28.097044   49.73460452]
Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant: 137180.0000000001


(g) Multiply the following matrices and also find covariance between matrices using NumPy:

    i. p = [[1, 2], [2, 3]]
       q = [[4, 5], [6, 7]]
    ii. p = [[1, 2], [2, 3], [4, 5]]
        q = [[4, 5, 1], [6, 7, 2]]
 

In [ ]:
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

prod1 = np.dot(p1, q1)
print("Product 1 :\n", prod1)

cov1 = np.cov(p1.T, q1.T)
print("Covariance 1 :\n", cov1)

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

prod2 = np.dot(p2, q2)
print("Product 2:\n", prod2)

pf = p2.flatten()
qf = q2.flatten()[:pf.size]

cov2 = np.cov(pf, qf)
print("Covariance 2:\n", cov2)




Product 1 :
 [[16 19]
 [26 31]]
Covariance 1 :
 [[0.5 0.5 1.  1. ]
 [0.5 0.5 1.  1. ]
 [1.  1.  2.  2. ]
 [1.  1.  2.  2. ]]
Product 2:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance 2:
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?


In [11]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

inprod = np.inner(x, y)
print("Inner product:\n", inprod)

outprod = np.outer(x.flatten(), y.flatten())
print("Outer product:\n", outprod)

cartprod = np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2)
print("Cartesian product:\n", cartprod)


Inner product:
 [[17 52]
 [13 62]]
Outer product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


Q2. (a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])

       i. Find element-wise absolute value
       ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each row.
       iii. Mean, Median and Standard Deviation of flattened array, of each column, and each row 


In [15]:
array = np.array([[1, -2, 3], [-4, 5, -6]])

absval = np.abs(array)
print("Absolute:\n", absval)

flat = array.flatten()
p25 = np.percentile(flat, 25)
p50 = np.percentile(flat, 50)  
p75 = np.percentile(flat, 75)
print("Flattened percentiles: 25th =", p25, ", 50th =", p50, ", 75th =", p75)

pcol = np.percentile(array, [25, 50, 75], axis=0)
print("Column-wise percentiles :\n", pcol)

prow = np.percentile(array, [25, 50, 75], axis=1)
print("Row-wise percentiles :\n", prow)

meanf = np.mean(flat)
medianf = np.median(flat)
stdf = np.std(flat)
print("Flattened: Mean =", meanf, ", Median =", medianf, ", Std Dev =", stdf)

print("Column-wise mean:", np.mean(array, axis=0))
print("Column-wise median:", np.median(array, axis=0))
print("Column-wise std:", np.std(array, axis=0))

print("Row-wise mean:", np.mean(array, axis=1))
print("Row-wise median:", np.median(array, axis=1))
print("Row-wise std:", np.std(array, axis=1))




Absolute:
 [[1 2 3]
 [4 5 6]]
Flattened percentiles: 25th = -3.5 , 50th = -0.5 , 75th = 2.5
Column-wise percentiles :
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Row-wise percentiles :
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Flattened: Mean = -0.5 , Median = -0.5 , Std Dev = 3.8622100754188224
Column-wise mean: [-1.5  1.5 -1.5]
Column-wise median: [-1.5  1.5 -1.5]
Column-wise std: [2.5 3.5 4.5]
Row-wise mean: [ 0.66666667 -1.66666667]
Row-wise median: [ 1. -4.]
Row-wise std: [2.05480467 4.78423336]


Q2.(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values

In [16]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

print("Floor:", np.floor(a))
print("Ceiling:", np.ceil(a))
print("Truncated:", np.trunc(a))
print("Rounded:", np.round(a))



Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling: [-1. -1. -0.  1.  2.  2.  3.]
Truncated: [-1. -1. -0.  0.  1.  1.  3.]
Rounded: [-2. -2. -0.  0.  2.  2.  3.]


Q3. (a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find

        i. Sorted array
        ii. Indices of sorted array
        iii. 4 smallest elements
        iv. 5 largest elements 


In [18]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

sortarr = np.sort(array)
print("Sorted array:", sortarr)

sortedindices = np.argsort(array)
print("Indices of sorted array:", sortedindices)

small4 = np.sort(array)[:4]
print("4 smallest elements:", small4)

large5 = np.sort(array)[-5:]
print("5 largest elements:", large5)



Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]


Q3.(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find

       i. Integer elements only
       ii. Float elements only 

In [21]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

integers = array[array == array.astype(int)]
print("Integer elements only:", integers)

floats = array[array != array.astype(int)]
print("Float elements only:", floats)


Integer elements only: [1. 2. 3. 2.]
Float elements only: [1.2 2.2]


Q4: (a) Write a function named img_to_array(path) that reads an image from a specified path and save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale images) 


In [23]:
%pip install opencv-python

   ---------------------------------------- 0.0/39.0 MB ? eta -:--:--
    --------------------------------------- 0.5/39.0 MB 3.4 MB/s eta 0:00:12
   - -------------------------------------- 1.3/39.0 MB 3.3 MB/s eta 0:00:12
   - -------------------------------------- 1.8/39.0 MB 3.2 MB/s eta 0:00:12
   -- ------------------------------------- 2.6/39.0 MB 3.3 MB/s eta 0:00:12
   --- ------------------------------------ 3.4/39.0 MB 3.4 MB/s eta 0:00:11
   ---- ----------------------------------- 4.2/39.0 MB 3.5 MB/s eta 0:00:10
   ----- ---------------------------------- 5.0/39.0 MB 3.5 MB/s eta 0:00:10
   ----- ---------------------------------- 5.5/39.0 MB 3.3 MB/s eta 0:00:11
   ------ --------------------------------- 6.3/39.0 MB 3.5 MB/s eta 0:00:10
   ------- -------------------------------- 7.3/39.0 MB 3.5 MB/s eta 0:00:09
   -------- ------------------------------- 8.4/39.0 MB 3.7 MB/s eta 0:00:09
   --------- ------------------------------ 9.2/39.0 MB 3.8 MB/s eta 0:00:08
   ---

  You can safely remove it manually.
  You can safely remove it manually.

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [31]:
import cv2

def img_to_array(path):
    img = cv2.imread(path)

    if img is None:
        print("Image not found or path is incorrect!")
        return

    if len(img.shape) == 2 or img.shape[2] == 1:
        print("Grayscale image detected.")
        np.savetxt("grayscale image.txt", img, fmt='%d')
        np.save("grayscale shape.npy", img.shape)
    else:
        print("RGB image detected.")
        imgrgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        np.savetxt("rgb image.txt", imgrgb.reshape(-1, 3), fmt='%d')
        np.save("rgb shape.npy", imgrgb.shape)

img_to_array(r"C:\Users\Dell\Desktop\Python\imageassignment1.png")



RGB image detected.


Q4. (b) Load the saved file into jupyter notebook,

In [35]:
rgb_flat = np.loadtxt("rgb image.txt", dtype=np.uint8)
rgb_shape = tuple(np.load("rgb shape.npy"))
rgb_image = rgb_flat.reshape(rgb_shape)

